/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.AplusContent;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing SearchContentPublishRecordsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchContentPublishRecordsResponseTests
    {
        // TODO uncomment below to declare an instance variable for SearchContentPublishRecordsResponse
        //private SearchContentPublishRecordsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchContentPublishRecordsResponse
            //instance = new SearchContentPublishRecordsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchContentPublishRecordsResponse
        /// </summary>
        [Test]
        public void SearchContentPublishRecordsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchContentPublishRecordsResponse
            //Assert.IsInstanceOfType<SearchContentPublishRecordsResponse> (instance, "variable 'instance' is a SearchContentPublishRecordsResponse");
        }


        /// <summary>
        /// Test the property 'PublishRecordList'
        /// </summary>
        [Test]
        public void PublishRecordListTest()
        {
            // TODO unit test for the property 'PublishRecordList'
        }

    }

}
