/* 
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.AplusContent;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing StandardSingleImageSpecsDetailModule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StandardSingleImageSpecsDetailModuleTests
    {
        // TODO uncomment below to declare an instance variable for StandardSingleImageSpecsDetailModule
        //private StandardSingleImageSpecsDetailModule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StandardSingleImageSpecsDetailModule
            //instance = new StandardSingleImageSpecsDetailModule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StandardSingleImageSpecsDetailModule
        /// </summary>
        [Test]
        public void StandardSingleImageSpecsDetailModuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StandardSingleImageSpecsDetailModule
            //Assert.IsInstanceOfType<StandardSingleImageSpecsDetailModule> (instance, "variable 'instance' is a StandardSingleImageSpecsDetailModule");
        }


        /// <summary>
        /// Test the property 'Headline'
        /// </summary>
        [Test]
        public void HeadlineTest()
        {
            // TODO unit test for the property 'Headline'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'DescriptionHeadline'
        /// </summary>
        [Test]
        public void DescriptionHeadlineTest()
        {
            // TODO unit test for the property 'DescriptionHeadline'
        }
        /// <summary>
        /// Test the property 'DescriptionBlock1'
        /// </summary>
        [Test]
        public void DescriptionBlock1Test()
        {
            // TODO unit test for the property 'DescriptionBlock1'
        }
        /// <summary>
        /// Test the property 'DescriptionBlock2'
        /// </summary>
        [Test]
        public void DescriptionBlock2Test()
        {
            // TODO unit test for the property 'DescriptionBlock2'
        }
        /// <summary>
        /// Test the property 'SpecificationHeadline'
        /// </summary>
        [Test]
        public void SpecificationHeadlineTest()
        {
            // TODO unit test for the property 'SpecificationHeadline'
        }
        /// <summary>
        /// Test the property 'SpecificationListBlock'
        /// </summary>
        [Test]
        public void SpecificationListBlockTest()
        {
            // TODO unit test for the property 'SpecificationListBlock'
        }
        /// <summary>
        /// Test the property 'SpecificationTextBlock'
        /// </summary>
        [Test]
        public void SpecificationTextBlockTest()
        {
            // TODO unit test for the property 'SpecificationTextBlock'
        }

    }

}
