/* 
 * Listings Items v2021-08-01
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * OpenAPI spec version: 2021-08-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.ListingsItems;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing Issue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IssueTests
    {
        // TODO uncomment below to declare an instance variable for Issue
        //private Issue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Issue
            //instance = new Issue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Issue
        /// </summary>
        [Test]
        public void IssueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Issue
            //Assert.IsInstanceOfType<Issue> (instance, "variable 'instance' is a Issue");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Test]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'AttributeNames'
        /// </summary>
        [Test]
        public void AttributeNamesTest()
        {
            // TODO unit test for the property 'AttributeNames'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Enforcements'
        /// </summary>
        [Test]
        public void EnforcementsTest()
        {
            // TODO unit test for the property 'Enforcements'
        }

    }

}
