/* 
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.FulfillmentOutbound
{
    /// <summary>
    /// The current delivery status of the package.
    /// </summary>
    /// <value>The current delivery status of the package.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CurrentStatus
    {
        
        /// <summary>
        /// Enum INTRANSIT for value: IN_TRANSIT
        /// </summary>
        [EnumMember(Value = "IN_TRANSIT")]
        INTRANSIT = 1,
        
        /// <summary>
        /// Enum DELIVERED for value: DELIVERED
        /// </summary>
        [EnumMember(Value = "DELIVERED")]
        DELIVERED = 2,
        
        /// <summary>
        /// Enum RETURNING for value: RETURNING
        /// </summary>
        [EnumMember(Value = "RETURNING")]
        RETURNING = 3,
        
        /// <summary>
        /// Enum RETURNED for value: RETURNED
        /// </summary>
        [EnumMember(Value = "RETURNED")]
        RETURNED = 4,
        
        /// <summary>
        /// Enum UNDELIVERABLE for value: UNDELIVERABLE
        /// </summary>
        [EnumMember(Value = "UNDELIVERABLE")]
        UNDELIVERABLE = 5,
        
        /// <summary>
        /// Enum DELAYED for value: DELAYED
        /// </summary>
        [EnumMember(Value = "DELAYED")]
        DELAYED = 6,
        
        /// <summary>
        /// Enum AVAILABLEFORPICKUP for value: AVAILABLE_FOR_PICKUP
        /// </summary>
        [EnumMember(Value = "AVAILABLE_FOR_PICKUP")]
        AVAILABLEFORPICKUP = 7,
        
        /// <summary>
        /// Enum CUSTOMERACTION for value: CUSTOMER_ACTION
        /// </summary>
        [EnumMember(Value = "CUSTOMER_ACTION")]
        CUSTOMERACTION = 8,
        
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 9,
        
        /// <summary>
        /// Enum OUTFORDELIVERY for value: OUT_FOR_DELIVERY
        /// </summary>
        [EnumMember(Value = "OUT_FOR_DELIVERY")]
        OUTFORDELIVERY = 10,
        
        /// <summary>
        /// Enum DELIVERYATTEMPTED for value: DELIVERY_ATTEMPTED
        /// </summary>
        [EnumMember(Value = "DELIVERY_ATTEMPTED")]
        DELIVERYATTEMPTED = 11,
        
        /// <summary>
        /// Enum PICKUPSUCCESSFUL for value: PICKUP_SUCCESSFUL
        /// </summary>
        [EnumMember(Value = "PICKUP_SUCCESSFUL")]
        PICKUPSUCCESSFUL = 12,
        
        /// <summary>
        /// Enum PICKUPCANCELLED for value: PICKUP_CANCELLED
        /// </summary>
        [EnumMember(Value = "PICKUP_CANCELLED")]
        PICKUPCANCELLED = 13,
        
        /// <summary>
        /// Enum PICKUPATTEMPTED for value: PICKUP_ATTEMPTED
        /// </summary>
        [EnumMember(Value = "PICKUP_ATTEMPTED")]
        PICKUPATTEMPTED = 14,
        
        /// <summary>
        /// Enum PICKUPSCHEDULED for value: PICKUP_SCHEDULED
        /// </summary>
        [EnumMember(Value = "PICKUP_SCHEDULED")]
        PICKUPSCHEDULED = 15,
        
        /// <summary>
        /// Enum RETURNREQUESTACCEPTED for value: RETURN_REQUEST_ACCEPTED
        /// </summary>
        [EnumMember(Value = "RETURN_REQUEST_ACCEPTED")]
        RETURNREQUESTACCEPTED = 16,
        
        /// <summary>
        /// Enum REFUNDISSUED for value: REFUND_ISSUED
        /// </summary>
        [EnumMember(Value = "REFUND_ISSUED")]
        REFUNDISSUED = 17,
        
        /// <summary>
        /// Enum RETURNRECEIVEDINFC for value: RETURN_RECEIVED_IN_FC
        /// </summary>
        [EnumMember(Value = "RETURN_RECEIVED_IN_FC")]
        RETURNRECEIVEDINFC = 18
    }

}
