/* 
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.FulfillmentOutbound
{
    /// <summary>
    /// A list of delivery offers, including offer expiration, earliest and latest date and time range, and the delivery offer policy.
    /// </summary>
    [DataContract]
    public partial class GetDeliveryOffersResult : IEquatable<GetDeliveryOffersResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDeliveryOffersResult" /> class.
        /// </summary>
        /// <param name="deliveryOffers">An array of delivery offers..</param>
        public GetDeliveryOffersResult(DeliveryOffersList deliveryOffers = default)
        {
            this.DeliveryOffers = deliveryOffers;
        }

        /// <summary>
        /// An array of delivery offers.
        /// </summary>
        /// <value>An array of delivery offers.</value>
        [DataMember(Name = "deliveryOffers", EmitDefaultValue = false)]
        public DeliveryOffersList DeliveryOffers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetDeliveryOffersResult {\n");
            sb.Append("  DeliveryOffers: ").Append(DeliveryOffers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetDeliveryOffersResult);
        }

        /// <summary>
        /// Returns true if GetDeliveryOffersResult instances are equal
        /// </summary>
        /// <param name="input">Instance of GetDeliveryOffersResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDeliveryOffersResult input)
        {
            if (input == null)
                return false;

            return
                (
                    this.DeliveryOffers == input.DeliveryOffers ||
                    (this.DeliveryOffers != null &&
                    this.DeliveryOffers.Equals(input.DeliveryOffers))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeliveryOffers != null)
                    hashCode = hashCode * 59 + this.DeliveryOffers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
