/* 
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Pricing;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Pricing.Test
{
    /// <summary>
    ///  Class for testing PrimeDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PrimeDetailsTests
    {
        // TODO uncomment below to declare an instance variable for PrimeDetails
        //private PrimeDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrimeDetails
            //instance = new PrimeDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrimeDetails
        /// </summary>
        [Test]
        public void PrimeDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PrimeDetails
            //Assert.IsInstanceOfType<PrimeDetails> (instance, "variable 'instance' is a PrimeDetails");
        }


        /// <summary>
        /// Test the property 'Eligibility'
        /// </summary>
        [Test]
        public void EligibilityTest()
        {
            // TODO unit test for the property 'Eligibility'
        }

    }

}
