/* 
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Amazon.SellingPartnerAPIAA.Clients.Client;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Replenishment;

namespace Amazon.SellingPartnerAPIAA.Clients.Replenishment.Test
{
    /// <summary>
    ///  Class for testing SellingpartnersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SellingpartnersApiTests
    {
        private SellingpartnersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to initialize instance for testing
            //instance = new SellingpartnersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellingpartnersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SellingpartnersApi
            //Assert.IsInstanceOfType(typeof(SellingpartnersApi), instance, "instance is a SellingpartnersApi");
        }

        
        /// <summary>
        /// Test GetSellingPartnerMetrics
        /// </summary>
        [Test]
        public void GetSellingPartnerMetricsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetSellingPartnerMetricsRequest body = null;
            //var response = instance.GetSellingPartnerMetrics(body);
            //Assert.IsInstanceOf<GetSellingPartnerMetricsResponse> (response, "response is GetSellingPartnerMetricsResponse");
        }
        
    }

}