/* 
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 *
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * OpenAPI spec version: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.ExternalFulfillmentShipments
{
    /// <summary>
    /// A shipment item&#39;s cancellation details.
    /// </summary>
    [DataContract]
    public partial class Cancellation : IEquatable<Cancellation>, IValidatableObject
    {
        /// <summary>
        /// The type of cancellation of the item in the shipment.
        /// </summary>
        /// <value>The type of cancellation of the item in the shipment.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CancellationTypeEnum
        {

            /// <summary>
            /// Enum SELLERREJECTED for value: SELLER_REJECTED
            /// </summary>
            [EnumMember(Value = "SELLER_REJECTED")]
            SELLERREJECTED = 1,

            /// <summary>
            /// Enum MARKETPLACECANCELLED for value: MARKETPLACE_CANCELLED
            /// </summary>
            [EnumMember(Value = "MARKETPLACE_CANCELLED")]
            MARKETPLACECANCELLED = 2,

            /// <summary>
            /// Enum SYSTEMCANCELLED for value: SYSTEM_CANCELLED
            /// </summary>
            [EnumMember(Value = "SYSTEM_CANCELLED")]
            SYSTEMCANCELLED = 3
        }

        /// <summary>
        /// The type of cancellation of the item in the shipment.
        /// </summary>
        /// <value>The type of cancellation of the item in the shipment.</value>
        [DataMember(Name = "cancellationType", EmitDefaultValue = false)]
        public CancellationTypeEnum CancellationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Cancellation" /> class.
        /// </summary>
        [JsonConstructor]
        protected Cancellation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Cancellation" /> class.
        /// </summary>
        /// <param name="cancelledQuantity">The number of items of this particular item which have been cancelled. (required).</param>
        /// <param name="cancelledTimestamp">The UNIX timestamp of when the line item was cancelled. (required).</param>
        /// <param name="cancellationType">The type of cancellation of the item in the shipment. (required).</param>
        /// <param name="cancellationReason">The reason for the cancellation of the shipment..</param>
        public Cancellation(int? cancelledQuantity = default, DateTime? cancelledTimestamp = default, CancellationTypeEnum cancellationType = default, string cancellationReason = default)
        {
            // to ensure "cancelledQuantity" is required (not null)
            if (cancelledQuantity == null)
            {
                throw new InvalidDataException("cancelledQuantity is a required property for Cancellation and cannot be null");
            }
            else
            {
                this.CancelledQuantity = cancelledQuantity;
            }
            // to ensure "cancelledTimestamp" is required (not null)
            if (cancelledTimestamp == null)
            {
                throw new InvalidDataException("cancelledTimestamp is a required property for Cancellation and cannot be null");
            }
            else
            {
                this.CancelledTimestamp = cancelledTimestamp;
            }
            // to ensure "cancellationType" is required (not null)
            if (cancellationType == null)
            {
                throw new InvalidDataException("cancellationType is a required property for Cancellation and cannot be null");
            }
            else
            {
                this.CancellationType = cancellationType;
            }
            this.CancellationReason = cancellationReason;
        }

        /// <summary>
        /// The number of items of this particular item which have been cancelled.
        /// </summary>
        /// <value>The number of items of this particular item which have been cancelled.</value>
        [DataMember(Name = "cancelledQuantity", EmitDefaultValue = false)]
        public int? CancelledQuantity { get; set; }

        /// <summary>
        /// The UNIX timestamp of when the line item was cancelled.
        /// </summary>
        /// <value>The UNIX timestamp of when the line item was cancelled.</value>
        [DataMember(Name = "cancelledTimestamp", EmitDefaultValue = false)]
        public DateTime? CancelledTimestamp { get; set; }


        /// <summary>
        /// The reason for the cancellation of the shipment.
        /// </summary>
        /// <value>The reason for the cancellation of the shipment.</value>
        [DataMember(Name = "cancellationReason", EmitDefaultValue = false)]
        public string CancellationReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Cancellation {\n");
            sb.Append("  CancelledQuantity: ").Append(CancelledQuantity).Append("\n");
            sb.Append("  CancelledTimestamp: ").Append(CancelledTimestamp).Append("\n");
            sb.Append("  CancellationType: ").Append(CancellationType).Append("\n");
            sb.Append("  CancellationReason: ").Append(CancellationReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Cancellation);
        }

        /// <summary>
        /// Returns true if Cancellation instances are equal
        /// </summary>
        /// <param name="input">Instance of Cancellation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Cancellation input)
        {
            if (input == null)
                return false;

            return
                (
                    this.CancelledQuantity == input.CancelledQuantity ||
                    (this.CancelledQuantity != null &&
                    this.CancelledQuantity.Equals(input.CancelledQuantity))
                ) &&
                (
                    this.CancelledTimestamp == input.CancelledTimestamp ||
                    (this.CancelledTimestamp != null &&
                    this.CancelledTimestamp.Equals(input.CancelledTimestamp))
                ) &&
                (
                    this.CancellationType == input.CancellationType ||
                    (this.CancellationType != null &&
                    this.CancellationType.Equals(input.CancellationType))
                ) &&
                (
                    this.CancellationReason == input.CancellationReason ||
                    (this.CancellationReason != null &&
                    this.CancellationReason.Equals(input.CancellationReason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CancelledQuantity != null)
                    hashCode = hashCode * 59 + this.CancelledQuantity.GetHashCode();
                if (this.CancelledTimestamp != null)
                    hashCode = hashCode * 59 + this.CancelledTimestamp.GetHashCode();
                if (this.CancellationType != null)
                    hashCode = hashCode * 59 + this.CancellationType.GetHashCode();
                if (this.CancellationReason != null)
                    hashCode = hashCode * 59 + this.CancellationReason.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CancelledQuantity (int?) minimum
            if (this.CancelledQuantity < (int?)1)
            {
                yield return new ValidationResult("Invalid value for CancelledQuantity, must be a value greater than or equal to 1.", new[] { "CancelledQuantity" });
            }

            yield break;
        }
    }

}
