/* 
 * The Selling Partner API for Orders
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * OpenAPI spec version: 2026-01-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.Orders
{
    /// <summary>
    /// Information about how the order item should be processed, packed, and shipped to the customer.
    /// </summary>
    [DataContract]
    public partial class ItemFulfillment :  IEquatable<ItemFulfillment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemFulfillment" /> class.
        /// </summary>
        /// <param name="quantityFulfilled">The number of units of this item that have been successfully processed and shipped..</param>
        /// <param name="quantityUnfulfilled">The number of units of this item that remain to be processed and shipped..</param>
        /// <param name="picking">Information related to the warehouse picking process for this item..</param>
        /// <param name="packing">Information related to the packaging process for this item..</param>
        /// <param name="shipping">Information related to the shipping and delivery process for this item..</param>
        public ItemFulfillment(int? quantityFulfilled = default(int?), int? quantityUnfulfilled = default(int?), ItemPicking picking = default(ItemPicking), ItemPacking packing = default(ItemPacking), ItemShipping shipping = default(ItemShipping))
        {
            this.QuantityFulfilled = quantityFulfilled;
            this.QuantityUnfulfilled = quantityUnfulfilled;
            this.Picking = picking;
            this.Packing = packing;
            this.Shipping = shipping;
        }
        
        /// <summary>
        /// The number of units of this item that have been successfully processed and shipped.
        /// </summary>
        /// <value>The number of units of this item that have been successfully processed and shipped.</value>
        [DataMember(Name="quantityFulfilled", EmitDefaultValue=false)]
        public int? QuantityFulfilled { get; set; }

        /// <summary>
        /// The number of units of this item that remain to be processed and shipped.
        /// </summary>
        /// <value>The number of units of this item that remain to be processed and shipped.</value>
        [DataMember(Name="quantityUnfulfilled", EmitDefaultValue=false)]
        public int? QuantityUnfulfilled { get; set; }

        /// <summary>
        /// Information related to the warehouse picking process for this item.
        /// </summary>
        /// <value>Information related to the warehouse picking process for this item.</value>
        [DataMember(Name="picking", EmitDefaultValue=false)]
        public ItemPicking Picking { get; set; }

        /// <summary>
        /// Information related to the packaging process for this item.
        /// </summary>
        /// <value>Information related to the packaging process for this item.</value>
        [DataMember(Name="packing", EmitDefaultValue=false)]
        public ItemPacking Packing { get; set; }

        /// <summary>
        /// Information related to the shipping and delivery process for this item.
        /// </summary>
        /// <value>Information related to the shipping and delivery process for this item.</value>
        [DataMember(Name="shipping", EmitDefaultValue=false)]
        public ItemShipping Shipping { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemFulfillment {\n");
            sb.Append("  QuantityFulfilled: ").Append(QuantityFulfilled).Append("\n");
            sb.Append("  QuantityUnfulfilled: ").Append(QuantityUnfulfilled).Append("\n");
            sb.Append("  Picking: ").Append(Picking).Append("\n");
            sb.Append("  Packing: ").Append(Packing).Append("\n");
            sb.Append("  Shipping: ").Append(Shipping).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemFulfillment);
        }

        /// <summary>
        /// Returns true if ItemFulfillment instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemFulfillment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemFulfillment input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuantityFulfilled == input.QuantityFulfilled ||
                    (this.QuantityFulfilled != null &&
                    this.QuantityFulfilled.Equals(input.QuantityFulfilled))
                ) && 
                (
                    this.QuantityUnfulfilled == input.QuantityUnfulfilled ||
                    (this.QuantityUnfulfilled != null &&
                    this.QuantityUnfulfilled.Equals(input.QuantityUnfulfilled))
                ) && 
                (
                    this.Picking == input.Picking ||
                    (this.Picking != null &&
                    this.Picking.Equals(input.Picking))
                ) && 
                (
                    this.Packing == input.Packing ||
                    (this.Packing != null &&
                    this.Packing.Equals(input.Packing))
                ) && 
                (
                    this.Shipping == input.Shipping ||
                    (this.Shipping != null &&
                    this.Shipping.Equals(input.Shipping))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuantityFulfilled != null)
                    hashCode = hashCode * 59 + this.QuantityFulfilled.GetHashCode();
                if (this.QuantityUnfulfilled != null)
                    hashCode = hashCode * 59 + this.QuantityUnfulfilled.GetHashCode();
                if (this.Picking != null)
                    hashCode = hashCode * 59 + this.Picking.GetHashCode();
                if (this.Packing != null)
                    hashCode = hashCode * 59 + this.Packing.GetHashCode();
                if (this.Shipping != null)
                    hashCode = hashCode * 59 + this.Shipping.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
