/* 
 * Orders v0
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.Orders
{
    /// <summary>
    /// Miscellaneous delivery attributes associated with the shipping address.
    /// </summary>
    /// <value>Miscellaneous delivery attributes associated with the shipping address.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum OtherDeliveryAttributes
    {
        
        /// <summary>
        /// Enum HASACCESSPOINT for value: HAS_ACCESS_POINT
        /// </summary>
        [EnumMember(Value = "HAS_ACCESS_POINT")]
        HASACCESSPOINT = 1,
        
        /// <summary>
        /// Enum PALLETENABLED for value: PALLET_ENABLED
        /// </summary>
        [EnumMember(Value = "PALLET_ENABLED")]
        PALLETENABLED = 2,
        
        /// <summary>
        /// Enum PALLETDISABLED for value: PALLET_DISABLED
        /// </summary>
        [EnumMember(Value = "PALLET_DISABLED")]
        PALLETDISABLED = 3
    }

}
