/* 
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Services;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing Recurrence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecurrenceTests
    {
        // TODO uncomment below to declare an instance variable for Recurrence
        //private Recurrence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Recurrence
            //instance = new Recurrence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Recurrence
        /// </summary>
        [Test]
        public void RecurrenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Recurrence
            //Assert.IsInstanceOfType<Recurrence> (instance, "variable 'instance' is a Recurrence");
        }


        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'DaysOfWeek'
        /// </summary>
        [Test]
        public void DaysOfWeekTest()
        {
            // TODO unit test for the property 'DaysOfWeek'
        }
        /// <summary>
        /// Test the property 'DaysOfMonth'
        /// </summary>
        [Test]
        public void DaysOfMonthTest()
        {
            // TODO unit test for the property 'DaysOfMonth'
        }

    }

}
