/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.MerchantFulfillment;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing Benefits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BenefitsTests
    {
        // TODO uncomment below to declare an instance variable for Benefits
        //private Benefits instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Benefits
            //instance = new Benefits();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Benefits
        /// </summary>
        [Test]
        public void BenefitsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Benefits
            //Assert.IsInstanceOfType<Benefits> (instance, "variable 'instance' is a Benefits");
        }


        /// <summary>
        /// Test the property 'IncludedBenefits'
        /// </summary>
        [Test]
        public void IncludedBenefitsTest()
        {
            // TODO unit test for the property 'IncludedBenefits'
        }
        /// <summary>
        /// Test the property 'ExcludedBenefits'
        /// </summary>
        [Test]
        public void ExcludedBenefitsTest()
        {
            // TODO unit test for the property 'ExcludedBenefits'
        }

    }

}
