/* 
 * Fulfillment Inbound v2024-03-20
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.FulfillmentInbound;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing PlacementOptionSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlacementOptionSummaryTests
    {
        // TODO uncomment below to declare an instance variable for PlacementOptionSummary
        //private PlacementOptionSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlacementOptionSummary
            //instance = new PlacementOptionSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlacementOptionSummary
        /// </summary>
        [Test]
        public void PlacementOptionSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlacementOptionSummary
            //Assert.IsInstanceOfType<PlacementOptionSummary> (instance, "variable 'instance' is a PlacementOptionSummary");
        }


        /// <summary>
        /// Test the property 'PlacementOptionId'
        /// </summary>
        [Test]
        public void PlacementOptionIdTest()
        {
            // TODO unit test for the property 'PlacementOptionId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
