/* 
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * OpenAPI spec version: 2020-11-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.AplusContent
{
    /// <summary>
    /// A reference to an image, hosted in the A+ Content media library.
    /// </summary>
    [DataContract]
    public partial class ImageComponent : IEquatable<ImageComponent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImageComponent" /> class.
        /// </summary>
        [JsonConstructor]
        protected ImageComponent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImageComponent" /> class.
        /// </summary>
        /// <param name="uploadDestinationId">This identifier is provided by the [Uploads API](https://developer-docs.amazon.com/sp-api/reference/welcome-to-api-references). (required).</param>
        /// <param name="imageCropSpecification">imageCropSpecification (required).</param>
        /// <param name="altText">The alternative text for the image. (required).</param>
        public ImageComponent(string uploadDestinationId = default, ImageCropSpecification imageCropSpecification = default, string altText = default)
        {
            // to ensure "uploadDestinationId" is required (not null)
            if (uploadDestinationId == null)
            {
                throw new InvalidDataException("uploadDestinationId is a required property for ImageComponent and cannot be null");
            }
            else
            {
                this.UploadDestinationId = uploadDestinationId;
            }
            // to ensure "imageCropSpecification" is required (not null)
            if (imageCropSpecification == null)
            {
                throw new InvalidDataException("imageCropSpecification is a required property for ImageComponent and cannot be null");
            }
            else
            {
                this.ImageCropSpecification = imageCropSpecification;
            }
            // to ensure "altText" is required (not null)
            if (altText == null)
            {
                throw new InvalidDataException("altText is a required property for ImageComponent and cannot be null");
            }
            else
            {
                this.AltText = altText;
            }
        }

        /// <summary>
        /// This identifier is provided by the [Uploads API](https://developer-docs.amazon.com/sp-api/reference/welcome-to-api-references).
        /// </summary>
        /// <value>This identifier is provided by the [Uploads API](https://developer-docs.amazon.com/sp-api/reference/welcome-to-api-references).</value>
        [DataMember(Name = "uploadDestinationId", EmitDefaultValue = false)]
        public string UploadDestinationId { get; set; }

        /// <summary>
        /// Gets or Sets ImageCropSpecification
        /// </summary>
        [DataMember(Name = "imageCropSpecification", EmitDefaultValue = false)]
        public ImageCropSpecification ImageCropSpecification { get; set; }

        /// <summary>
        /// The alternative text for the image.
        /// </summary>
        /// <value>The alternative text for the image.</value>
        [DataMember(Name = "altText", EmitDefaultValue = false)]
        public string AltText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ImageComponent {\n");
            sb.Append("  UploadDestinationId: ").Append(UploadDestinationId).Append("\n");
            sb.Append("  ImageCropSpecification: ").Append(ImageCropSpecification).Append("\n");
            sb.Append("  AltText: ").Append(AltText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImageComponent);
        }

        /// <summary>
        /// Returns true if ImageComponent instances are equal
        /// </summary>
        /// <param name="input">Instance of ImageComponent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImageComponent input)
        {
            if (input == null)
                return false;

            return
                (
                    this.UploadDestinationId == input.UploadDestinationId ||
                    (this.UploadDestinationId != null &&
                    this.UploadDestinationId.Equals(input.UploadDestinationId))
                ) &&
                (
                    this.ImageCropSpecification == input.ImageCropSpecification ||
                    (this.ImageCropSpecification != null &&
                    this.ImageCropSpecification.Equals(input.ImageCropSpecification))
                ) &&
                (
                    this.AltText == input.AltText ||
                    (this.AltText != null &&
                    this.AltText.Equals(input.AltText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UploadDestinationId != null)
                    hashCode = hashCode * 59 + this.UploadDestinationId.GetHashCode();
                if (this.ImageCropSpecification != null)
                    hashCode = hashCode * 59 + this.ImageCropSpecification.GetHashCode();
                if (this.AltText != null)
                    hashCode = hashCode * 59 + this.AltText.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UploadDestinationId (string) minLength
            if (this.UploadDestinationId != null && this.UploadDestinationId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for UploadDestinationId, length must be greater than 1.", new[] { "UploadDestinationId" });
            }

            // AltText (string) maxLength
            if (this.AltText != null && this.AltText.Length > 100)
            {
                yield return new ValidationResult("Invalid value for AltText, length must be less than 100.", new[] { "AltText" });
            }

            // AltText (string) minLength
            if (this.AltText != null && this.AltText.Length < 1)
            {
                yield return new ValidationResult("Invalid value for AltText, length must be greater than 1.", new[] { "AltText" });
            }

            yield break;
        }
    }

}
