/* 
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.FbaInventory;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing InventoryDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InventoryDetailsTests
    {
        // TODO uncomment below to declare an instance variable for InventoryDetails
        //private InventoryDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InventoryDetails
            //instance = new InventoryDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InventoryDetails
        /// </summary>
        [Test]
        public void InventoryDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InventoryDetails
            //Assert.IsInstanceOfType<InventoryDetails> (instance, "variable 'instance' is a InventoryDetails");
        }


        /// <summary>
        /// Test the property 'FulfillableQuantity'
        /// </summary>
        [Test]
        public void FulfillableQuantityTest()
        {
            // TODO unit test for the property 'FulfillableQuantity'
        }
        /// <summary>
        /// Test the property 'InboundWorkingQuantity'
        /// </summary>
        [Test]
        public void InboundWorkingQuantityTest()
        {
            // TODO unit test for the property 'InboundWorkingQuantity'
        }
        /// <summary>
        /// Test the property 'InboundShippedQuantity'
        /// </summary>
        [Test]
        public void InboundShippedQuantityTest()
        {
            // TODO unit test for the property 'InboundShippedQuantity'
        }
        /// <summary>
        /// Test the property 'InboundReceivingQuantity'
        /// </summary>
        [Test]
        public void InboundReceivingQuantityTest()
        {
            // TODO unit test for the property 'InboundReceivingQuantity'
        }
        /// <summary>
        /// Test the property 'ReservedQuantity'
        /// </summary>
        [Test]
        public void ReservedQuantityTest()
        {
            // TODO unit test for the property 'ReservedQuantity'
        }
        /// <summary>
        /// Test the property 'ResearchingQuantity'
        /// </summary>
        [Test]
        public void ResearchingQuantityTest()
        {
            // TODO unit test for the property 'ResearchingQuantity'
        }
        /// <summary>
        /// Test the property 'UnfulfillableQuantity'
        /// </summary>
        [Test]
        public void UnfulfillableQuantityTest()
        {
            // TODO unit test for the property 'UnfulfillableQuantity'
        }

    }

}
