/* 
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * OpenAPI spec version: 2024-06-19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Finances;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing RelatedIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelatedIdentifierTests
    {
        // TODO uncomment below to declare an instance variable for RelatedIdentifier
        //private RelatedIdentifier instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedIdentifier
            //instance = new RelatedIdentifier();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedIdentifier
        /// </summary>
        [Test]
        public void RelatedIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelatedIdentifier
            //Assert.IsInstanceOfType<RelatedIdentifier> (instance, "variable 'instance' is a RelatedIdentifier");
        }


        /// <summary>
        /// Test the property 'RelatedIdentifierName'
        /// </summary>
        [Test]
        public void RelatedIdentifierNameTest()
        {
            // TODO unit test for the property 'RelatedIdentifierName'
        }
        /// <summary>
        /// Test the property 'RelatedIdentifierValue'
        /// </summary>
        [Test]
        public void RelatedIdentifierValueTest()
        {
            // TODO unit test for the property 'RelatedIdentifierValue'
        }

    }

}
