/* 
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: 2021-12-28
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.VendorDirectFulfillmentShipping;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing LabelData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LabelDataTests
    {
        // TODO uncomment below to declare an instance variable for LabelData
        //private LabelData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LabelData
            //instance = new LabelData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LabelData
        /// </summary>
        [Test]
        public void LabelDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LabelData
            //Assert.IsInstanceOfType<LabelData> (instance, "variable 'instance' is a LabelData");
        }


        /// <summary>
        /// Test the property 'PackageIdentifier'
        /// </summary>
        [Test]
        public void PackageIdentifierTest()
        {
            // TODO unit test for the property 'PackageIdentifier'
        }
        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Test]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }
        /// <summary>
        /// Test the property 'ShipMethod'
        /// </summary>
        [Test]
        public void ShipMethodTest()
        {
            // TODO unit test for the property 'ShipMethod'
        }
        /// <summary>
        /// Test the property 'ShipMethodName'
        /// </summary>
        [Test]
        public void ShipMethodNameTest()
        {
            // TODO unit test for the property 'ShipMethodName'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
