/* 
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * OpenAPI spec version: 2021-12-28
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.VendorDirectFulfillmentShipping;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing SubmitShipmentConfirmationsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmitShipmentConfirmationsRequestTests
    {
        // TODO uncomment below to declare an instance variable for SubmitShipmentConfirmationsRequest
        //private SubmitShipmentConfirmationsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmitShipmentConfirmationsRequest
            //instance = new SubmitShipmentConfirmationsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmitShipmentConfirmationsRequest
        /// </summary>
        [Test]
        public void SubmitShipmentConfirmationsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmitShipmentConfirmationsRequest
            //Assert.IsInstanceOfType<SubmitShipmentConfirmationsRequest> (instance, "variable 'instance' is a SubmitShipmentConfirmationsRequest");
        }


        /// <summary>
        /// Test the property 'ShipmentConfirmations'
        /// </summary>
        [Test]
        public void ShipmentConfirmationsTest()
        {
            // TODO unit test for the property 'ShipmentConfirmations'
        }

    }

}
