/* 
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.CustomerFeedback
{
    /// <summary>
    /// The browse node review topic.
    /// </summary>
    [DataContract]
    public partial class BrowseNodeReviewTopic : IEquatable<BrowseNodeReviewTopic>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReviewTopic" /> class.
        /// </summary>
        [JsonConstructor]
        protected BrowseNodeReviewTopic() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReviewTopic" /> class.
        /// </summary>
        /// <param name="topic">The name browse node review topic. (required).</param>
        /// <param name="browseNodeMetrics">The percentage of browse node reviews that mention the topic, and the effect the topic has on the star rating. (required).</param>
        /// <param name="reviewSnippets">A list of up to three snippets from reviews that contain the topic. This value is &#x60;null&#x60; if there aren&#39;t enough review snippets for the topic..</param>
        /// <param name="subtopics">A list of the five subtopics that occur most frequently. This value is &#x60;null&#x60; if there are no subtopics..</param>
        public BrowseNodeReviewTopic(string topic = default, BrowseNodeReviewTopicMetrics browseNodeMetrics = default, List<string> reviewSnippets = default, List<BrowseNodeSubtopic> subtopics = default)
        {
            // to ensure "topic" is required (not null)
            if (topic == null)
            {
                throw new InvalidDataException("topic is a required property for BrowseNodeReviewTopic and cannot be null");
            }
            else
            {
                this.Topic = topic;
            }
            // to ensure "browseNodeMetrics" is required (not null)
            if (browseNodeMetrics == null)
            {
                throw new InvalidDataException("browseNodeMetrics is a required property for BrowseNodeReviewTopic and cannot be null");
            }
            else
            {
                this.BrowseNodeMetrics = browseNodeMetrics;
            }
            this.ReviewSnippets = reviewSnippets;
            this.Subtopics = subtopics;
        }

        /// <summary>
        /// The name browse node review topic.
        /// </summary>
        /// <value>The name browse node review topic.</value>
        [DataMember(Name = "topic", EmitDefaultValue = false)]
        public string Topic { get; set; }

        /// <summary>
        /// The percentage of browse node reviews that mention the topic, and the effect the topic has on the star rating.
        /// </summary>
        /// <value>The percentage of browse node reviews that mention the topic, and the effect the topic has on the star rating.</value>
        [DataMember(Name = "browseNodeMetrics", EmitDefaultValue = false)]
        public BrowseNodeReviewTopicMetrics BrowseNodeMetrics { get; set; }

        /// <summary>
        /// A list of up to three snippets from reviews that contain the topic. This value is &#x60;null&#x60; if there aren&#39;t enough review snippets for the topic.
        /// </summary>
        /// <value>A list of up to three snippets from reviews that contain the topic. This value is &#x60;null&#x60; if there aren&#39;t enough review snippets for the topic.</value>
        [DataMember(Name = "reviewSnippets", EmitDefaultValue = false)]
        public List<string> ReviewSnippets { get; set; }

        /// <summary>
        /// A list of the five subtopics that occur most frequently. This value is &#x60;null&#x60; if there are no subtopics.
        /// </summary>
        /// <value>A list of the five subtopics that occur most frequently. This value is &#x60;null&#x60; if there are no subtopics.</value>
        [DataMember(Name = "subtopics", EmitDefaultValue = false)]
        public List<BrowseNodeSubtopic> Subtopics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BrowseNodeReviewTopic {\n");
            sb.Append("  Topic: ").Append(Topic).Append("\n");
            sb.Append("  BrowseNodeMetrics: ").Append(BrowseNodeMetrics).Append("\n");
            sb.Append("  ReviewSnippets: ").Append(ReviewSnippets).Append("\n");
            sb.Append("  Subtopics: ").Append(Subtopics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BrowseNodeReviewTopic);
        }

        /// <summary>
        /// Returns true if BrowseNodeReviewTopic instances are equal
        /// </summary>
        /// <param name="input">Instance of BrowseNodeReviewTopic to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrowseNodeReviewTopic input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Topic == input.Topic ||
                    (this.Topic != null &&
                    this.Topic.Equals(input.Topic))
                ) &&
                (
                    this.BrowseNodeMetrics == input.BrowseNodeMetrics ||
                    (this.BrowseNodeMetrics != null &&
                    this.BrowseNodeMetrics.Equals(input.BrowseNodeMetrics))
                ) &&
                (
                    this.ReviewSnippets == input.ReviewSnippets ||
                    this.ReviewSnippets != null &&
                    this.ReviewSnippets.SequenceEqual(input.ReviewSnippets)
                ) &&
                (
                    this.Subtopics == input.Subtopics ||
                    this.Subtopics != null &&
                    this.Subtopics.SequenceEqual(input.Subtopics)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Topic != null)
                    hashCode = hashCode * 59 + this.Topic.GetHashCode();
                if (this.BrowseNodeMetrics != null)
                    hashCode = hashCode * 59 + this.BrowseNodeMetrics.GetHashCode();
                if (this.ReviewSnippets != null)
                    hashCode = hashCode * 59 + this.ReviewSnippets.GetHashCode();
                if (this.Subtopics != null)
                    hashCode = hashCode * 59 + this.Subtopics.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
