/* 
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 
 *
 * OpenAPI spec version: 2024-05-09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.Awd
{
    /// <summary>
    /// Response containing the reference identifier for the newly created/updated replenishment order consisting of the order ID.
    /// </summary>
    [DataContract]
    public partial class ReplenishmentOrderReference : IEquatable<ReplenishmentOrderReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplenishmentOrderReference" /> class.
        /// </summary>
        [JsonConstructor]
        protected ReplenishmentOrderReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplenishmentOrderReference" /> class.
        /// </summary>
        /// <param name="orderId">Order ID of the Replenishment order. (required).</param>
        public ReplenishmentOrderReference(string orderId = default)
        {
            // to ensure "orderId" is required (not null)
            if (orderId == null)
            {
                throw new InvalidDataException("orderId is a required property for ReplenishmentOrderReference and cannot be null");
            }
            else
            {
                this.OrderId = orderId;
            }
        }

        /// <summary>
        /// Order ID of the Replenishment order.
        /// </summary>
        /// <value>Order ID of the Replenishment order.</value>
        [DataMember(Name = "orderId", EmitDefaultValue = false)]
        public string OrderId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReplenishmentOrderReference {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReplenishmentOrderReference);
        }

        /// <summary>
        /// Returns true if ReplenishmentOrderReference instances are equal
        /// </summary>
        /// <param name="input">Instance of ReplenishmentOrderReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplenishmentOrderReference input)
        {
            if (input == null)
                return false;

            return
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
