/* 
 * Selling Partner API for Shipment Invoicing
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.ShipmentInvoicing;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing ShipmentInvoiceStatusInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShipmentInvoiceStatusInfoTests
    {
        // TODO uncomment below to declare an instance variable for ShipmentInvoiceStatusInfo
        //private ShipmentInvoiceStatusInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShipmentInvoiceStatusInfo
            //instance = new ShipmentInvoiceStatusInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShipmentInvoiceStatusInfo
        /// </summary>
        [Test]
        public void ShipmentInvoiceStatusInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShipmentInvoiceStatusInfo
            //Assert.IsInstanceOfType<ShipmentInvoiceStatusInfo> (instance, "variable 'instance' is a ShipmentInvoiceStatusInfo");
        }


        /// <summary>
        /// Test the property 'AmazonShipmentId'
        /// </summary>
        [Test]
        public void AmazonShipmentIdTest()
        {
            // TODO unit test for the property 'AmazonShipmentId'
        }
        /// <summary>
        /// Test the property 'InvoiceStatus'
        /// </summary>
        [Test]
        public void InvoiceStatusTest()
        {
            // TODO unit test for the property 'InvoiceStatus'
        }

    }

}
