/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.MerchantFulfillment
{
    /// <summary>
    /// The label format.
    /// </summary>
    /// <value>The label format.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum LabelFormat
    {
        
        /// <summary>
        /// Enum PDF for value: PDF
        /// </summary>
        [EnumMember(Value = "PDF")]
        PDF = 1,
        
        /// <summary>
        /// Enum PNG for value: PNG
        /// </summary>
        [EnumMember(Value = "PNG")]
        PNG = 2,
        
        /// <summary>
        /// Enum ZPL203 for value: ZPL203
        /// </summary>
        [EnumMember(Value = "ZPL203")]
        ZPL203 = 3,
        
        /// <summary>
        /// Enum ZPL300 for value: ZPL300
        /// </summary>
        [EnumMember(Value = "ZPL300")]
        ZPL300 = 4,
        
        /// <summary>
        /// Enum ShippingServiceDefault for value: ShippingServiceDefault
        /// </summary>
        [EnumMember(Value = "ShippingServiceDefault")]
        ShippingServiceDefault = 5
    }

}
