/* 
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.MerchantFulfillment
{
    /// <summary>
    /// Type for the RateItem.
    /// </summary>
    /// <value>Type for the RateItem.</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum RateItemType
    {

        /// <summary>
        /// Enum INCLUDED for value: INCLUDED
        /// </summary>
        [EnumMember(Value = "INCLUDED")]
        INCLUDED = 1
    }

}
