/* 
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Replenishment;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing ListOfferMetricsResponseOffer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListOfferMetricsResponseOfferTests
    {
        // TODO uncomment below to declare an instance variable for ListOfferMetricsResponseOffer
        //private ListOfferMetricsResponseOffer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListOfferMetricsResponseOffer
            //instance = new ListOfferMetricsResponseOffer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListOfferMetricsResponseOffer
        /// </summary>
        [Test]
        public void ListOfferMetricsResponseOfferInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListOfferMetricsResponseOffer
            //Assert.IsInstanceOfType<ListOfferMetricsResponseOffer> (instance, "variable 'instance' is a ListOfferMetricsResponseOffer");
        }


        /// <summary>
        /// Test the property 'Asin'
        /// </summary>
        [Test]
        public void AsinTest()
        {
            // TODO unit test for the property 'Asin'
        }
        /// <summary>
        /// Test the property 'NotDeliveredDueToOOS'
        /// </summary>
        [Test]
        public void NotDeliveredDueToOOSTest()
        {
            // TODO unit test for the property 'NotDeliveredDueToOOS'
        }
        /// <summary>
        /// Test the property 'TotalSubscriptionsRevenue'
        /// </summary>
        [Test]
        public void TotalSubscriptionsRevenueTest()
        {
            // TODO unit test for the property 'TotalSubscriptionsRevenue'
        }
        /// <summary>
        /// Test the property 'ShippedSubscriptionUnits'
        /// </summary>
        [Test]
        public void ShippedSubscriptionUnitsTest()
        {
            // TODO unit test for the property 'ShippedSubscriptionUnits'
        }
        /// <summary>
        /// Test the property 'ActiveSubscriptions'
        /// </summary>
        [Test]
        public void ActiveSubscriptionsTest()
        {
            // TODO unit test for the property 'ActiveSubscriptions'
        }
        /// <summary>
        /// Test the property 'RevenuePenetration'
        /// </summary>
        [Test]
        public void RevenuePenetrationTest()
        {
            // TODO unit test for the property 'RevenuePenetration'
        }
        /// <summary>
        /// Test the property 'LostRevenueDueToOOS'
        /// </summary>
        [Test]
        public void LostRevenueDueToOOSTest()
        {
            // TODO unit test for the property 'LostRevenueDueToOOS'
        }
        /// <summary>
        /// Test the property 'CouponsRevenuePenetration'
        /// </summary>
        [Test]
        public void CouponsRevenuePenetrationTest()
        {
            // TODO unit test for the property 'CouponsRevenuePenetration'
        }
        /// <summary>
        /// Test the property 'Next30DayTotalSubscriptionsRevenue'
        /// </summary>
        [Test]
        public void Next30DayTotalSubscriptionsRevenueTest()
        {
            // TODO unit test for the property 'Next30DayTotalSubscriptionsRevenue'
        }
        /// <summary>
        /// Test the property 'Next60DayTotalSubscriptionsRevenue'
        /// </summary>
        [Test]
        public void Next60DayTotalSubscriptionsRevenueTest()
        {
            // TODO unit test for the property 'Next60DayTotalSubscriptionsRevenue'
        }
        /// <summary>
        /// Test the property 'Next90DayTotalSubscriptionsRevenue'
        /// </summary>
        [Test]
        public void Next90DayTotalSubscriptionsRevenueTest()
        {
            // TODO unit test for the property 'Next90DayTotalSubscriptionsRevenue'
        }
        /// <summary>
        /// Test the property 'Next30DayShippedSubscriptionUnits'
        /// </summary>
        [Test]
        public void Next30DayShippedSubscriptionUnitsTest()
        {
            // TODO unit test for the property 'Next30DayShippedSubscriptionUnits'
        }
        /// <summary>
        /// Test the property 'Next60DayShippedSubscriptionUnits'
        /// </summary>
        [Test]
        public void Next60DayShippedSubscriptionUnitsTest()
        {
            // TODO unit test for the property 'Next60DayShippedSubscriptionUnits'
        }
        /// <summary>
        /// Test the property 'Next90DayShippedSubscriptionUnits'
        /// </summary>
        [Test]
        public void Next90DayShippedSubscriptionUnitsTest()
        {
            // TODO unit test for the property 'Next90DayShippedSubscriptionUnits'
        }
        /// <summary>
        /// Test the property 'TimeInterval'
        /// </summary>
        [Test]
        public void TimeIntervalTest()
        {
            // TODO unit test for the property 'TimeInterval'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

    }

}
