/* 
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Replenishment;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing ListOffersRequestFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListOffersRequestFiltersTests
    {
        // TODO uncomment below to declare an instance variable for ListOffersRequestFilters
        //private ListOffersRequestFilters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListOffersRequestFilters
            //instance = new ListOffersRequestFilters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListOffersRequestFilters
        /// </summary>
        [Test]
        public void ListOffersRequestFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListOffersRequestFilters
            //Assert.IsInstanceOfType<ListOffersRequestFilters> (instance, "variable 'instance' is a ListOffersRequestFilters");
        }


        /// <summary>
        /// Test the property 'MarketplaceId'
        /// </summary>
        [Test]
        public void MarketplaceIdTest()
        {
            // TODO unit test for the property 'MarketplaceId'
        }
        /// <summary>
        /// Test the property 'Skus'
        /// </summary>
        [Test]
        public void SkusTest()
        {
            // TODO unit test for the property 'Skus'
        }
        /// <summary>
        /// Test the property 'Asins'
        /// </summary>
        [Test]
        public void AsinsTest()
        {
            // TODO unit test for the property 'Asins'
        }
        /// <summary>
        /// Test the property 'Eligibilities'
        /// </summary>
        [Test]
        public void EligibilitiesTest()
        {
            // TODO unit test for the property 'Eligibilities'
        }
        /// <summary>
        /// Test the property 'Preferences'
        /// </summary>
        [Test]
        public void PreferencesTest()
        {
            // TODO unit test for the property 'Preferences'
        }
        /// <summary>
        /// Test the property 'Promotions'
        /// </summary>
        [Test]
        public void PromotionsTest()
        {
            // TODO unit test for the property 'Promotions'
        }
        /// <summary>
        /// Test the property 'ProgramTypes'
        /// </summary>
        [Test]
        public void ProgramTypesTest()
        {
            // TODO unit test for the property 'ProgramTypes'
        }

    }

}
