/* 
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * OpenAPI spec version: 2022-03-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.EasyShip
{
    /// <summary>
    /// An error code that identifies the type of error that occurred. The error codes listed below are specific to the Easy Ship section.
    /// </summary>
    /// <value>An error code that identifies the type of error that occurred. The error codes listed below are specific to the Easy Ship section.</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum Code
    {

        /// <summary>
        /// Enum InvalidInput for value: InvalidInput
        /// </summary>
        [EnumMember(Value = "InvalidInput")]
        InvalidInput = 1,

        /// <summary>
        /// Enum InvalidTimeSlotId for value: InvalidTimeSlotId
        /// </summary>
        [EnumMember(Value = "InvalidTimeSlotId")]
        InvalidTimeSlotId = 2,

        /// <summary>
        /// Enum ScheduledPackageAlreadyExists for value: ScheduledPackageAlreadyExists
        /// </summary>
        [EnumMember(Value = "ScheduledPackageAlreadyExists")]
        ScheduledPackageAlreadyExists = 3,

        /// <summary>
        /// Enum ScheduleWindowExpired for value: ScheduleWindowExpired
        /// </summary>
        [EnumMember(Value = "ScheduleWindowExpired")]
        ScheduleWindowExpired = 4,

        /// <summary>
        /// Enum RetryableAfterGettingNewSlots for value: RetryableAfterGettingNewSlots
        /// </summary>
        [EnumMember(Value = "RetryableAfterGettingNewSlots")]
        RetryableAfterGettingNewSlots = 5,

        /// <summary>
        /// Enum TimeSlotNotAvailable for value: TimeSlotNotAvailable
        /// </summary>
        [EnumMember(Value = "TimeSlotNotAvailable")]
        TimeSlotNotAvailable = 6,

        /// <summary>
        /// Enum ResourceNotFound for value: ResourceNotFound
        /// </summary>
        [EnumMember(Value = "ResourceNotFound")]
        ResourceNotFound = 7,

        /// <summary>
        /// Enum InvalidOrderState for value: InvalidOrderState
        /// </summary>
        [EnumMember(Value = "InvalidOrderState")]
        InvalidOrderState = 8,

        /// <summary>
        /// Enum RegionNotSupported for value: RegionNotSupported
        /// </summary>
        [EnumMember(Value = "RegionNotSupported")]
        RegionNotSupported = 9,

        /// <summary>
        /// Enum OrderNotEligibleForRescheduling for value: OrderNotEligibleForRescheduling
        /// </summary>
        [EnumMember(Value = "OrderNotEligibleForRescheduling")]
        OrderNotEligibleForRescheduling = 10,

        /// <summary>
        /// Enum InternalServerError for value: InternalServerError
        /// </summary>
        [EnumMember(Value = "InternalServerError")]
        InternalServerError = 11
    }

}
