/* 
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easyship-api-v2022-03-23-use-case-guide#marketplace-support-table) for the differences in Easy Ship operations by marketplace.
 *
 * OpenAPI spec version: 2022-03-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.EasyShip
{
    /// <summary>
    /// Request to update the time slot of a package.
    /// </summary>
    [DataContract]
    public partial class UpdatePackageDetails :  IEquatable<UpdatePackageDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePackageDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePackageDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePackageDetails" /> class.
        /// </summary>
        /// <param name="scheduledPackageId">scheduledPackageId (required).</param>
        /// <param name="packageTimeSlot">packageTimeSlot (required).</param>
        public UpdatePackageDetails(ScheduledPackageId scheduledPackageId = default(ScheduledPackageId), TimeSlot packageTimeSlot = default(TimeSlot))
        {
            // to ensure "scheduledPackageId" is required (not null)
            if (scheduledPackageId == null)
            {
                throw new InvalidDataException("scheduledPackageId is a required property for UpdatePackageDetails and cannot be null");
            }
            else
            {
                this.ScheduledPackageId = scheduledPackageId;
            }
            // to ensure "packageTimeSlot" is required (not null)
            if (packageTimeSlot == null)
            {
                throw new InvalidDataException("packageTimeSlot is a required property for UpdatePackageDetails and cannot be null");
            }
            else
            {
                this.PackageTimeSlot = packageTimeSlot;
            }
        }
        
        /// <summary>
        /// Gets or Sets ScheduledPackageId
        /// </summary>
        [DataMember(Name="scheduledPackageId", EmitDefaultValue=false)]
        public ScheduledPackageId ScheduledPackageId { get; set; }

        /// <summary>
        /// Gets or Sets PackageTimeSlot
        /// </summary>
        [DataMember(Name="packageTimeSlot", EmitDefaultValue=false)]
        public TimeSlot PackageTimeSlot { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdatePackageDetails {\n");
            sb.Append("  ScheduledPackageId: ").Append(ScheduledPackageId).Append("\n");
            sb.Append("  PackageTimeSlot: ").Append(PackageTimeSlot).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdatePackageDetails);
        }

        /// <summary>
        /// Returns true if UpdatePackageDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdatePackageDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatePackageDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ScheduledPackageId == input.ScheduledPackageId ||
                    (this.ScheduledPackageId != null &&
                    this.ScheduledPackageId.Equals(input.ScheduledPackageId))
                ) && 
                (
                    this.PackageTimeSlot == input.PackageTimeSlot ||
                    (this.PackageTimeSlot != null &&
                    this.PackageTimeSlot.Equals(input.PackageTimeSlot))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ScheduledPackageId != null)
                    hashCode = hashCode * 59 + this.ScheduledPackageId.GetHashCode();
                if (this.PackageTimeSlot != null)
                    hashCode = hashCode * 59 + this.PackageTimeSlot.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
