/* 
 * Vendor Invoices v1
 *
 * The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.VendorInvoices;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing CreditNoteDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditNoteDetailsTests
    {
        // TODO uncomment below to declare an instance variable for CreditNoteDetails
        //private CreditNoteDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditNoteDetails
            //instance = new CreditNoteDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditNoteDetails
        /// </summary>
        [Test]
        public void CreditNoteDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditNoteDetails
            //Assert.IsInstanceOfType<CreditNoteDetails> (instance, "variable 'instance' is a CreditNoteDetails");
        }


        /// <summary>
        /// Test the property 'ReferenceInvoiceNumber'
        /// </summary>
        [Test]
        public void ReferenceInvoiceNumberTest()
        {
            // TODO unit test for the property 'ReferenceInvoiceNumber'
        }
        /// <summary>
        /// Test the property 'DebitNoteNumber'
        /// </summary>
        [Test]
        public void DebitNoteNumberTest()
        {
            // TODO unit test for the property 'DebitNoteNumber'
        }
        /// <summary>
        /// Test the property 'ReturnsReferenceNumber'
        /// </summary>
        [Test]
        public void ReturnsReferenceNumberTest()
        {
            // TODO unit test for the property 'ReturnsReferenceNumber'
        }
        /// <summary>
        /// Test the property 'GoodsReturnDate'
        /// </summary>
        [Test]
        public void GoodsReturnDateTest()
        {
            // TODO unit test for the property 'GoodsReturnDate'
        }
        /// <summary>
        /// Test the property 'RmaId'
        /// </summary>
        [Test]
        public void RmaIdTest()
        {
            // TODO unit test for the property 'RmaId'
        }
        /// <summary>
        /// Test the property 'CoopReferenceNumber'
        /// </summary>
        [Test]
        public void CoopReferenceNumberTest()
        {
            // TODO unit test for the property 'CoopReferenceNumber'
        }
        /// <summary>
        /// Test the property 'ConsignorsReferenceNumber'
        /// </summary>
        [Test]
        public void ConsignorsReferenceNumberTest()
        {
            // TODO unit test for the property 'ConsignorsReferenceNumber'
        }

    }

}
