/* 
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.SellerWallet
{
    /// <summary>
    /// Represents current status of the transaction.
    /// </summary>
    /// <value>Represents current status of the transaction.</value>

    [JsonConverter(typeof(StringEnumConverter))]

    public enum TransactionStatus
    {

        /// <summary>
        /// Enum EXPIRED for value: EXPIRED
        /// </summary>
        [EnumMember(Value = "EXPIRED")]
        EXPIRED = 1,

        /// <summary>
        /// Enum FAILED for value: FAILED
        /// </summary>
        [EnumMember(Value = "FAILED")]
        FAILED = 2,

        /// <summary>
        /// Enum FAILEDCREDITSAPPLIED for value: FAILED_CREDITS_APPLIED
        /// </summary>
        [EnumMember(Value = "FAILED_CREDITS_APPLIED")]
        FAILEDCREDITSAPPLIED = 3,

        /// <summary>
        /// Enum INPROGRESS for value: IN_PROGRESS
        /// </summary>
        [EnumMember(Value = "IN_PROGRESS")]
        INPROGRESS = 4,

        /// <summary>
        /// Enum PENDINGUSERAPPROVAL for value: PENDING_USER_APPROVAL
        /// </summary>
        [EnumMember(Value = "PENDING_USER_APPROVAL")]
        PENDINGUSERAPPROVAL = 5,

        /// <summary>
        /// Enum SUCCESSFUL for value: SUCCESSFUL
        /// </summary>
        [EnumMember(Value = "SUCCESSFUL")]
        SUCCESSFUL = 6
    }

}
